version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: jotjournal-postgres
    restart: always
    env_file: server/.env
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10

  jotjournal:
    build:
      context: .
    container_name: jotjournal-app
    image: jotjournal-app
    depends_on:
      postgres:
        condition: service_healthy
    env_file: server/.env
    ports:
      - "8080:8080"
