services:
  postgres:
    image: postgres:15
    container_name: jotjournal-postgres
    restart: always
    env_file: server/.env
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - jotjournal

  valkey:
    image: valkey/valkey
    container_name: jotjournal-valkey
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - jotjournal

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports: ["3000:3000"]
    env_file: client/.env
    volumes:
      - type: bind
        source: ./client
        target: /app
      - /app/node_modules      # keep deps in container
    networks:
      - jotjournal

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: jotjournal-backend
    image: jotjournal-backend
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    env_file: server/.env
    ports:
      - "8080:8080"
    networks:
      - jotjournal

networks:
  jotjournal:

volumes: 
  next-cache: {} 

